name: app_mascotas
description: "Una aplicación para reportar mascotas perdidas y encontradas, con funcionalidades de geolocalización y almacenamiento en la nube."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  flutter_dotenv: ^5.2.1
  dropdown_search: ^5.0.3
  permission_handler: ^11.3.0
  geolocator: ^14.0.2
  image_picker: ^0.8.5+3
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  firebase_core: ^3.15.2
  path_provider: ^2.0.14
  firebase_auth: ^5.7.0
  flutter_svg: ^2.2.0
  firebase_messaging: ^15.2.10 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^1.2.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true
  web: false

flutter_launcher_icons:
  image_path: assets/images/splash.png
  android: true 
  ios: true